services:
  backend:
    image: Jonathan43/fastapi-backend:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app 

  frontend:
    image: Jonathan43/streamlit-frontend:latest
    build:
      context: .s
      dockerfile: frontend.Dockerfile
    container_name: streamlit-frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    volumes:
      - ./streamlit:/streamlit
